-- GENERATED by scripts/gen.py from catalog/engines.json. Do not edit by hand.
-- Requires: 00_wrappers.sql (extension + fdw), a foreign server named `serpapi`, and 10_private.sql.

-- private foreign tables, one per engine plus `search` and `account`
import foreign schema serpapi from server serpapi into serpapi_private;

-- ===== google =====
create type serpapi."google_result" as (
  search_id text,
  page int,
  "position" int,
  "title" text,
  "link" text,
  "displayed_link" text,
  "snippet" text,
  "date" text,
  "source" text,
  "favicon" text,
  "thumbnail" text,
  raw jsonb
);

create function serpapi."google"(
  "q" text,
  "gl" text default null,
  "hl" text default null,
  "location" text default null,
  "google_domain" text default null,
  "num" int default null,
  "tbs" text default null,
  "safe" text default null,
  pages int default 1
) returns setof serpapi."google_result"
language plpgsql volatile security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
declare
  t0 timestamptz := clock_timestamp();
  n int;
begin
  perform serpapi_private.check_quota(coalesce(pages, 1));
  return query
    select f.search_id, f.page, f."position", f."title", f."link", f."displayed_link", f."snippet", f."date", f."source", f."favicon", f."thumbnail", f.raw
    from serpapi_private."google" f
    where f."q" = coalesce("q", '')
      and f."gl" = coalesce("gl", '')
      and f."hl" = coalesce("hl", '')
      and f."location" = coalesce("location", '')
      and f."google_domain" = coalesce("google_domain", '')
      and f."num" = coalesce("num", -1)
      and f."tbs" = coalesce("tbs", '')
      and f."safe" = coalesce("safe", '')
      and f.pages = coalesce(pages, 1);
  get diagnostics n = row_count;
  perform serpapi_private.log_request('google', jsonb_strip_nulls(jsonb_build_object('q', "q", 'gl', "gl", 'hl', "hl", 'location', "location", 'google_domain', "google_domain", 'num', "num", 'tbs', "tbs", 'safe', "safe", 'pages', pages)), n, extract(milliseconds from clock_timestamp() - t0)::int);
end $$;
comment on function serpapi."google" is 'Google Search organic results';
revoke execute on function serpapi."google" from public;

create function serpapi."replay_google"(search_id text)
returns setof serpapi."google_result"
language plpgsql stable security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
begin
  return query
    select f.search_id, f.page, f."position", f."title", f."link", f."displayed_link", f."snippet", f."date", f."source", f."favicon", f."thumbnail", f.raw
    from serpapi_private."google" f
    where f.search_id = search_id;
end $$;
comment on function serpapi."replay_google" is 'Re-read a past google search from the SerpApi archive (free for 31 days).';
revoke execute on function serpapi."replay_google" from public;


-- ===== google_light =====
create type serpapi."google_light_result" as (
  search_id text,
  page int,
  "position" int,
  "title" text,
  "link" text,
  "displayed_link" text,
  "snippet" text,
  "date" text,
  "source" text,
  raw jsonb
);

create function serpapi."google_light"(
  "q" text,
  "gl" text default null,
  "hl" text default null,
  "google_domain" text default null,
  "num" int default null,
  pages int default 1
) returns setof serpapi."google_light_result"
language plpgsql volatile security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
declare
  t0 timestamptz := clock_timestamp();
  n int;
begin
  perform serpapi_private.check_quota(coalesce(pages, 1));
  return query
    select f.search_id, f.page, f."position", f."title", f."link", f."displayed_link", f."snippet", f."date", f."source", f.raw
    from serpapi_private."google_light" f
    where f."q" = coalesce("q", '')
      and f."gl" = coalesce("gl", '')
      and f."hl" = coalesce("hl", '')
      and f."google_domain" = coalesce("google_domain", '')
      and f."num" = coalesce("num", -1)
      and f.pages = coalesce(pages, 1);
  get diagnostics n = row_count;
  perform serpapi_private.log_request('google_light', jsonb_strip_nulls(jsonb_build_object('q', "q", 'gl', "gl", 'hl', "hl", 'google_domain', "google_domain", 'num', "num", 'pages', pages)), n, extract(milliseconds from clock_timestamp() - t0)::int);
end $$;
comment on function serpapi."google_light" is 'Google Light Search organic results (faster, fewer blocks). Note: `location` is temporarily unsupported by SerpApi on this engine (Sep 2026).';
revoke execute on function serpapi."google_light" from public;

create function serpapi."replay_google_light"(search_id text)
returns setof serpapi."google_light_result"
language plpgsql stable security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
begin
  return query
    select f.search_id, f.page, f."position", f."title", f."link", f."displayed_link", f."snippet", f."date", f."source", f.raw
    from serpapi_private."google_light" f
    where f.search_id = search_id;
end $$;
comment on function serpapi."replay_google_light" is 'Re-read a past google_light search from the SerpApi archive (free for 31 days).';
revoke execute on function serpapi."replay_google_light" from public;


-- ===== google_shopping =====
create type serpapi."google_shopping_result" as (
  search_id text,
  page int,
  "position" int,
  "title" text,
  "source" text,
  "price" text,
  "extracted_price" numeric,
  "old_price" text,
  "extracted_old_price" numeric,
  "rating" numeric,
  "reviews" int,
  "delivery" text,
  "tag" text,
  "product_id" text,
  "product_link" text,
  "immersive_product_page_token" text,
  "thumbnail" text,
  "extensions" jsonb,
  raw jsonb
);

create function serpapi."google_shopping"(
  "q" text,
  "gl" text default null,
  "hl" text default null,
  "location" text default null,
  "google_domain" text default null,
  "min_price" numeric default null,
  "max_price" numeric default null,
  "sort_by" text default null,
  "on_sale" boolean default false,
  "num" int default null,
  pages int default 1
) returns setof serpapi."google_shopping_result"
language plpgsql volatile security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
declare
  t0 timestamptz := clock_timestamp();
  n int;
begin
  perform serpapi_private.check_quota(coalesce(pages, 1));
  return query
    select f.search_id, f.page, f."position", f."title", f."source", f."price", f."extracted_price", f."old_price", f."extracted_old_price", f."rating", f."reviews", f."delivery", f."tag", f."product_id", f."product_link", f."immersive_product_page_token", f."thumbnail", f."extensions", f.raw
    from serpapi_private."google_shopping" f
    where f."q" = coalesce("q", '')
      and f."gl" = coalesce("gl", '')
      and f."hl" = coalesce("hl", '')
      and f."location" = coalesce("location", '')
      and f."google_domain" = coalesce("google_domain", '')
      and f."min_price" = coalesce("min_price", -1)
      and f."max_price" = coalesce("max_price", -1)
      and f."sort_by" = coalesce("sort_by", '')
      and f."on_sale" = coalesce("on_sale", false)
      and f."num" = coalesce("num", -1)
      and f.pages = coalesce(pages, 1);
  get diagnostics n = row_count;
  perform serpapi_private.log_request('google_shopping', jsonb_strip_nulls(jsonb_build_object('q', "q", 'gl', "gl", 'hl', "hl", 'location', "location", 'google_domain', "google_domain", 'min_price', "min_price", 'max_price', "max_price", 'sort_by', "sort_by", 'on_sale', "on_sale", 'num', "num", 'pages', pages)), n, extract(milliseconds from clock_timestamp() - t0)::int);
end $$;
comment on function serpapi."google_shopping" is 'Google Shopping results. SerpApi ignores `start` on this engine (~40 results per request), so pagination is none.';
revoke execute on function serpapi."google_shopping" from public;

create function serpapi."replay_google_shopping"(search_id text)
returns setof serpapi."google_shopping_result"
language plpgsql stable security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
begin
  return query
    select f.search_id, f.page, f."position", f."title", f."source", f."price", f."extracted_price", f."old_price", f."extracted_old_price", f."rating", f."reviews", f."delivery", f."tag", f."product_id", f."product_link", f."immersive_product_page_token", f."thumbnail", f."extensions", f.raw
    from serpapi_private."google_shopping" f
    where f.search_id = search_id;
end $$;
comment on function serpapi."replay_google_shopping" is 'Re-read a past google_shopping search from the SerpApi archive (free for 31 days).';
revoke execute on function serpapi."replay_google_shopping" from public;


-- ===== amazon =====
create type serpapi."amazon_result" as (
  search_id text,
  page int,
  "position" int,
  "asin" text,
  "title" text,
  "link" text,
  "price" text,
  "extracted_price" numeric,
  "old_price" text,
  "extracted_old_price" numeric,
  "rating" numeric,
  "reviews" int,
  "bought_last_month" text,
  "sponsored" boolean,
  "prime" boolean,
  "thumbnail" text,
  "delivery" jsonb,
  "variants" jsonb,
  raw jsonb
);

create function serpapi."amazon"(
  "q" text,
  "gl" text default null,
  "hl" text default null,
  "amazon_domain" text default null,
  "language" text default null,
  "delivery_zip" text default null,
  "s" text default null,
  pages int default 1
) returns setof serpapi."amazon_result"
language plpgsql volatile security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
declare
  t0 timestamptz := clock_timestamp();
  n int;
begin
  perform serpapi_private.check_quota(coalesce(pages, 1));
  return query
    select f.search_id, f.page, f."position", f."asin", f."title", f."link", f."price", f."extracted_price", f."old_price", f."extracted_old_price", f."rating", f."reviews", f."bought_last_month", f."sponsored", f."prime", f."thumbnail", f."delivery", f."variants", f.raw
    from serpapi_private."amazon" f
    where f."q" = coalesce("q", '')
      and f."gl" = coalesce("gl", '')
      and f."hl" = coalesce("hl", '')
      and f."amazon_domain" = coalesce("amazon_domain", '')
      and f."language" = coalesce("language", '')
      and f."delivery_zip" = coalesce("delivery_zip", '')
      and f."s" = coalesce("s", '')
      and f.pages = coalesce(pages, 1);
  get diagnostics n = row_count;
  perform serpapi_private.log_request('amazon', jsonb_strip_nulls(jsonb_build_object('q', "q", 'gl', "gl", 'hl', "hl", 'amazon_domain', "amazon_domain", 'language', "language", 'delivery_zip', "delivery_zip", 's', "s", 'pages', pages)), n, extract(milliseconds from clock_timestamp() - t0)::int);
end $$;
comment on function serpapi."amazon" is 'Amazon Search results. Query parameter is `k`; `amazon_domain` selects the marketplace (amazon.in for India).';
revoke execute on function serpapi."amazon" from public;

create function serpapi."replay_amazon"(search_id text)
returns setof serpapi."amazon_result"
language plpgsql stable security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
begin
  return query
    select f.search_id, f.page, f."position", f."asin", f."title", f."link", f."price", f."extracted_price", f."old_price", f."extracted_old_price", f."rating", f."reviews", f."bought_last_month", f."sponsored", f."prime", f."thumbnail", f."delivery", f."variants", f.raw
    from serpapi_private."amazon" f
    where f.search_id = search_id;
end $$;
comment on function serpapi."replay_amazon" is 'Re-read a past amazon search from the SerpApi archive (free for 31 days).';
revoke execute on function serpapi."replay_amazon" from public;


-- ===== google_jobs =====
create type serpapi."google_jobs_result" as (
  search_id text,
  page int,
  "title" text,
  "company_name" text,
  "job_location" text,
  "via" text,
  "posted_at" text,
  "schedule_type" text,
  "salary" text,
  "work_from_home" boolean,
  "description" text,
  "share_link" text,
  "job_id" text,
  "apply_options" jsonb,
  "job_highlights" jsonb,
  "thumbnail" text,
  raw jsonb
);

create function serpapi."google_jobs"(
  "q" text,
  "gl" text default null,
  "hl" text default null,
  "location" text default null,
  "google_domain" text default null,
  "lrad" int default null,
  "uds" text default null,
  pages int default 1
) returns setof serpapi."google_jobs_result"
language plpgsql volatile security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
declare
  t0 timestamptz := clock_timestamp();
  n int;
begin
  perform serpapi_private.check_quota(coalesce(pages, 1));
  return query
    select f.search_id, f.page, f."title", f."company_name", f."job_location", f."via", f."posted_at", f."schedule_type", f."salary", f."work_from_home", f."description", f."share_link", f."job_id", f."apply_options", f."job_highlights", f."thumbnail", f.raw
    from serpapi_private."google_jobs" f
    where f."q" = coalesce("q", '')
      and f."gl" = coalesce("gl", '')
      and f."hl" = coalesce("hl", '')
      and f."location" = coalesce("location", '')
      and f."google_domain" = coalesce("google_domain", '')
      and f."lrad" = coalesce("lrad", -1)
      and f."uds" = coalesce("uds", '')
      and f.pages = coalesce(pages, 1);
  get diagnostics n = row_count;
  perform serpapi_private.log_request('google_jobs', jsonb_strip_nulls(jsonb_build_object('q', "q", 'gl', "gl", 'hl', "hl", 'location', "location", 'google_domain', "google_domain", 'lrad', "lrad", 'uds', "uds", 'pages', pages)), n, extract(milliseconds from clock_timestamp() - t0)::int);
end $$;
comment on function serpapi."google_jobs" is 'Google Jobs results. 10 per page, token pagination. SerpApi reports intermittent empties on this engine (Sep 2026); the wrapper surfaces those as zero rows plus a notice.';
revoke execute on function serpapi."google_jobs" from public;

create function serpapi."replay_google_jobs"(search_id text)
returns setof serpapi."google_jobs_result"
language plpgsql stable security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
begin
  return query
    select f.search_id, f.page, f."title", f."company_name", f."job_location", f."via", f."posted_at", f."schedule_type", f."salary", f."work_from_home", f."description", f."share_link", f."job_id", f."apply_options", f."job_highlights", f."thumbnail", f.raw
    from serpapi_private."google_jobs" f
    where f.search_id = search_id;
end $$;
comment on function serpapi."replay_google_jobs" is 'Re-read a past google_jobs search from the SerpApi archive (free for 31 days).';
revoke execute on function serpapi."replay_google_jobs" from public;


-- ===== google_maps =====
create type serpapi."google_maps_result" as (
  search_id text,
  page int,
  "position" int,
  "title" text,
  "place_id" text,
  "data_id" text,
  "data_cid" text,
  "latitude" numeric,
  "longitude" numeric,
  "rating" numeric,
  "reviews" int,
  "price" text,
  "type" text,
  "types" jsonb,
  "address" text,
  "open_now" text,
  "phone" text,
  "website" text,
  "description" text,
  "service_options" jsonb,
  "thumbnail" text,
  raw jsonb
);

create function serpapi."google_maps"(
  "q" text,
  "gl" text default null,
  "hl" text default null,
  "ll" text default null,
  "location" text default null,
  "google_domain" text default null,
  "min_rating" numeric default null,
  "open_state" text default null,
  pages int default 1
) returns setof serpapi."google_maps_result"
language plpgsql volatile security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
declare
  t0 timestamptz := clock_timestamp();
  n int;
begin
  perform serpapi_private.check_quota(coalesce(pages, 1));
  return query
    select f.search_id, f.page, f."position", f."title", f."place_id", f."data_id", f."data_cid", f."latitude", f."longitude", f."rating", f."reviews", f."price", f."type", f."types", f."address", f."open_now", f."phone", f."website", f."description", f."service_options", f."thumbnail", f.raw
    from serpapi_private."google_maps" f
    where f."q" = coalesce("q", '')
      and f."gl" = coalesce("gl", '')
      and f."hl" = coalesce("hl", '')
      and f."ll" = coalesce("ll", '')
      and f."location" = coalesce("location", '')
      and f."google_domain" = coalesce("google_domain", '')
      and f."min_rating" = coalesce("min_rating", -1)
      and f."open_state" = coalesce("open_state", '')
      and f.pages = coalesce(pages, 1);
  get diagnostics n = row_count;
  perform serpapi_private.log_request('google_maps', jsonb_strip_nulls(jsonb_build_object('q', "q", 'gl', "gl", 'hl', "hl", 'll', "ll", 'location', "location", 'google_domain', "google_domain", 'min_rating', "min_rating", 'open_state', "open_state", 'pages', pages)), n, extract(milliseconds from clock_timestamp() - t0)::int);
end $$;
comment on function serpapi."google_maps" is 'Google Maps local results (type=search). 20 per page via `start`. Prefer `ll` (''@lat,lng,14z'') for precise geo; `location` also works.';
revoke execute on function serpapi."google_maps" from public;

create function serpapi."replay_google_maps"(search_id text)
returns setof serpapi."google_maps_result"
language plpgsql stable security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
begin
  return query
    select f.search_id, f.page, f."position", f."title", f."place_id", f."data_id", f."data_cid", f."latitude", f."longitude", f."rating", f."reviews", f."price", f."type", f."types", f."address", f."open_now", f."phone", f."website", f."description", f."service_options", f."thumbnail", f.raw
    from serpapi_private."google_maps" f
    where f.search_id = search_id;
end $$;
comment on function serpapi."replay_google_maps" is 'Re-read a past google_maps search from the SerpApi archive (free for 31 days).';
revoke execute on function serpapi."replay_google_maps" from public;


-- ===== google_maps_reviews =====
create type serpapi."google_maps_reviews_result" as (
  search_id text,
  page int,
  "review_id" text,
  "rating" numeric,
  "date" text,
  "iso_date" text,
  "snippet" text,
  "original_snippet" text,
  "translated_snippet" text,
  "likes" int,
  "user_name" text,
  "contributor_id" text,
  "local_guide" boolean,
  "user_reviews" int,
  "user_photos" int,
  "response" jsonb,
  raw jsonb
);

create function serpapi."google_maps_reviews"(
  "data_id" text default null,
  "gl" text default null,
  "hl" text default null,
  "place_id" text default null,
  "sort_by" text default null,
  "topic_id" text default null,
  "num" int default null,
  pages int default 1
) returns setof serpapi."google_maps_reviews_result"
language plpgsql volatile security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
declare
  t0 timestamptz := clock_timestamp();
  n int;
begin
  perform serpapi_private.check_quota(coalesce(pages, 1));
  return query
    select f.search_id, f.page, f."review_id", f."rating", f."date", f."iso_date", f."snippet", f."original_snippet", f."translated_snippet", f."likes", f."user_name", f."contributor_id", f."local_guide", f."user_reviews", f."user_photos", f."response", f.raw
    from serpapi_private."google_maps_reviews" f
    where f."data_id" = coalesce("data_id", '')
      and f."gl" = coalesce("gl", '')
      and f."hl" = coalesce("hl", '')
      and f."place_id" = coalesce("place_id", '')
      and f."sort_by" = coalesce("sort_by", '')
      and f."topic_id" = coalesce("topic_id", '')
      and f."num" = coalesce("num", -1)
      and f.pages = coalesce(pages, 1);
  get diagnostics n = row_count;
  perform serpapi_private.log_request('google_maps_reviews', jsonb_strip_nulls(jsonb_build_object('data_id', "data_id", 'gl', "gl", 'hl', "hl", 'place_id', "place_id", 'sort_by', "sort_by", 'topic_id', "topic_id", 'num', "num", 'pages', pages)), n, extract(milliseconds from clock_timestamp() - t0)::int);
end $$;
comment on function serpapi."google_maps_reviews" is 'Reviews for one place. Requires `data_id` (from google_maps) or `place_id`. First page is 8 reviews, then up to 20 per page via token.';
revoke execute on function serpapi."google_maps_reviews" from public;

create function serpapi."replay_google_maps_reviews"(search_id text)
returns setof serpapi."google_maps_reviews_result"
language plpgsql stable security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
begin
  return query
    select f.search_id, f.page, f."review_id", f."rating", f."date", f."iso_date", f."snippet", f."original_snippet", f."translated_snippet", f."likes", f."user_name", f."contributor_id", f."local_guide", f."user_reviews", f."user_photos", f."response", f.raw
    from serpapi_private."google_maps_reviews" f
    where f.search_id = search_id;
end $$;
comment on function serpapi."replay_google_maps_reviews" is 'Re-read a past google_maps_reviews search from the SerpApi archive (free for 31 days).';
revoke execute on function serpapi."replay_google_maps_reviews" from public;


-- ===== google_news =====
create type serpapi."google_news_result" as (
  search_id text,
  page int,
  "position" int,
  "title" text,
  "link" text,
  "source_name" text,
  "source_icon" text,
  "authors" jsonb,
  "date" text,
  "iso_date" text,
  "snippet" text,
  "thumbnail" text,
  "stories" jsonb,
  raw jsonb
);

create function serpapi."google_news"(
  "q" text default null,
  "gl" text default null,
  "hl" text default null,
  "topic_token" text default null,
  "story_token" text default null,
  "publication_token" text default null,
  "so" int default null,
  pages int default 1
) returns setof serpapi."google_news_result"
language plpgsql volatile security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
declare
  t0 timestamptz := clock_timestamp();
  n int;
begin
  perform serpapi_private.check_quota(coalesce(pages, 1));
  return query
    select f.search_id, f.page, f."position", f."title", f."link", f."source_name", f."source_icon", f."authors", f."date", f."iso_date", f."snippet", f."thumbnail", f."stories", f.raw
    from serpapi_private."google_news" f
    where f."q" = coalesce("q", '')
      and f."gl" = coalesce("gl", '')
      and f."hl" = coalesce("hl", '')
      and f."topic_token" = coalesce("topic_token", '')
      and f."story_token" = coalesce("story_token", '')
      and f."publication_token" = coalesce("publication_token", '')
      and f."so" = coalesce("so", -1)
      and f.pages = coalesce(pages, 1);
  get diagnostics n = row_count;
  perform serpapi_private.log_request('google_news', jsonb_strip_nulls(jsonb_build_object('q', "q", 'gl', "gl", 'hl', "hl", 'topic_token', "topic_token", 'story_token', "story_token", 'publication_token', "publication_token", 'so', "so", 'pages', pages)), n, extract(milliseconds from clock_timestamp() - t0)::int);
end $$;
comment on function serpapi."google_news" is 'Google News results. No pagination. Regional editions exist for hi/ta/te/ml/bn/mr; `hl=kn` falls back to Hindi.';
revoke execute on function serpapi."google_news" from public;

create function serpapi."replay_google_news"(search_id text)
returns setof serpapi."google_news_result"
language plpgsql stable security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
begin
  return query
    select f.search_id, f.page, f."position", f."title", f."link", f."source_name", f."source_icon", f."authors", f."date", f."iso_date", f."snippet", f."thumbnail", f."stories", f.raw
    from serpapi_private."google_news" f
    where f.search_id = search_id;
end $$;
comment on function serpapi."replay_google_news" is 'Re-read a past google_news search from the SerpApi archive (free for 31 days).';
revoke execute on function serpapi."replay_google_news" from public;


-- ===== generic =====
-- generic access to any engine: one row per page
create function serpapi.search(engine text, params jsonb default '{}'::jsonb, pages int default 1)
returns table (search_id text, page int, result jsonb)
language plpgsql volatile security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
declare
  t0 timestamptz := clock_timestamp();
  n int;
begin
  perform serpapi_private.check_quota(coalesce(pages, 1));
  return query
    select f.search_id, f.page, f.result
    from serpapi_private.search f
    where f.engine = engine
      and f.params = coalesce(params, '{}'::jsonb)
      and f.pages = coalesce(pages, 1);
  get diagnostics n = row_count;
  perform serpapi_private.log_request(engine, coalesce(params, '{}'::jsonb) || jsonb_build_object('pages', pages), n, extract(milliseconds from clock_timestamp() - t0)::int);
end $$;
comment on function serpapi.search is 'Any SerpApi engine. params are passed through as query parameters (api_key/engine/output are ignored).';
revoke execute on function serpapi.search from public;

-- same, but the response rendered as Markdown (fetched free from the archive)
create function serpapi.search_md(engine text, params jsonb default '{}'::jsonb)
returns table (search_id text, markdown text)
language plpgsql volatile security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
begin
  perform serpapi_private.check_quota(1);
  return query
    select f.search_id, f.markdown
    from serpapi_private.search f
    where f.engine = engine
      and f.params = coalesce(params, '{}'::jsonb)
      and f.pages = 1;
end $$;
revoke execute on function serpapi.search_md from public;

-- free re-read of any past search, whatever the engine
create function serpapi.replay(search_id text)
returns jsonb
language plpgsql stable security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
declare r jsonb;
begin
  select f.result into r from serpapi_private.search f where f.search_id = search_id limit 1;
  return r;
end $$;
revoke execute on function serpapi.replay from public;

create function serpapi.replay_md(search_id text)
returns text
language plpgsql stable security definer
set search_path = ''
set statement_timeout = '25s'
set plan_cache_mode = 'force_custom_plan'
as $$
#variable_conflict use_variable
declare r text;
begin
  select f.markdown into r from serpapi_private.search f where f.search_id = search_id limit 1;
  return r;
end $$;
revoke execute on function serpapi.replay_md from public;

-- live account status (never returns the api key)
create function serpapi.account()
returns table (
  account_email text, plan_name text, searches_per_month int, plan_searches_left int,
  extra_credits int, total_searches_left int, this_month_usage int, this_hour_searches int,
  account_rate_limit_per_hour int
)
language sql volatile security definer
set search_path = ''
set statement_timeout = '15s'
as $$
  select a.account_email, a.plan_name, a.searches_per_month, a.plan_searches_left,
         a.extra_credits, a.total_searches_left, a.this_month_usage, a.this_hour_searches,
         a.account_rate_limit_per_hour
  from serpapi_private.account a;
$$;
revoke execute on function serpapi.account from public;
